### ISSUE TITLE
Einthusan Error - On opening any of the directories

### ISSUE THREAD

**Issue by BeanedPaths** [eintamil/repository.eintamil#24]
Error observed when tried to open any of the directories 

- Error statement - Einthusan error, Check the log for more details
- Kodi version - v19.1 
- Addon version - Einthusan Video Addon - Version 3
- Device type - Hisense Android TV (Android 9)
-  kodi.log

```
> 2021-06-29 22:50:31.181 T:6911     INFO <general>: Python interpreter stopped
> 2021-06-29 22:50:31.184 T:6910    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.einthusan3/?description&lang=tamil&mode=11&name=Staff%20Picks&url=https%3a%2f%2feinthusan.tv%2fmovie%2fresults%2f%3ffind%3dStaffPick%26lang%3dtamil
> 2021-06-29 22:50:31.187 T:5120    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.einthusan3/?description&lang=tamil&mode=11&name=Staff%20Picks&url=https%3a%2f%2feinthusan.tv%2fmovie%2fresults%2f%3ffind%3dStaffPick%26lang%3dtamil) failed
> 2021-06-29 22:54:28.204 T:6979     INFO <general>: initializing python engine.
> 2021-06-29 22:54:29.854 T:6979     INFO <general>: browse_home: https://einthusan.tv/movie/browse/?lang=tamil
> 2021-06-29 22:54:31.716 T:6979    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                                     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                                    Error Type: <class 'IndexError'>
>                                                    Error Contents: list index out of range
>                                                    Traceback (most recent call last):
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.einthusan3/main.py", line 628, in <module>
>                                                        function_map[mode](name, url, language, mode)
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.einthusan3/main.py", line 274, in browse_home
>                                                        list_videos(url, "home")
>                                                      File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.einthusan3/main.py", line 285, in list_videos
>                                                        if video_list[-1][6] != "":
>                                                    IndexError: list index out of range
>                                                    -->End of Python script error report<--
>                                                    
> 2021-06-29 22:54:32.484 T:6979     INFO <general>: Python interpreter stopped
> 2021-06-29 22:54:32.500 T:6978    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.einthusan3/?description&lang=tamil&mode=3&name=Featured&url=https%3a%2f%2feinthusan.tv%2fmovie%2fbrowse%2f%3flang%3dtamil
> 2021-06-29 22:54:32.503 T:5120    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.einthusan3/?description&lang=tamil&mode=3&name=Featured&url=https%3a%2f%2feinthusan.tv%2fmovie%2fbrowse%2f%3flang%3dtamil) failed
> 2021-06-29 22:55:48.310 T:7003     INFO <general>: initializing python engine.
> 2021-06-29 22:55:50.806 T:5120     INFO <general>: Loading skin file: DialogTextViewer.xml, load type: KEEP_IN_MEMORY
> 2021-06-29 22:55:50.818 T:7003     INFO <general>: CPythonInvoker(15, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.logviewer/default.py): script successfully run
> 2021-06-29 22:55:51.315 T:7003     INFO <general>: Python interpreter stopped
> 2021-06-29 22:55:56.180 T:5120  WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 7, because topmost modal dialog closing animation is running
> 2021-06-29 22:55:57.052 T:7004     INFO <general>: initializing python engine.
> 2021-06-29 22:56:01.465 T:7004     INFO <general>: CPythonInvoker(16, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.logviewer/default.py): script successfully run
> 2021-06-29 22:56:01.997 T:7004     INFO <general>: Python interpreter stopped
> 2021-06-29 22:56:58.038 T:5120     INFO <general>: CWinSystemAndroid::DestroyWindow
> 2021-06-29 22:56:58.112 T:5050  WARNING <general>: CPeripheralBusAndroid: failed to update input device with ID 2 because it couldn't be found
> 2021-06-29 22:58:37.621 T:5050     INFO <general>: CPeripheralBusAndroid: input device "Hisense" with ID 6 removed
> 2021-06-29 22:58:37.622 T:5050     INFO <general>: UnregisterRemovedDevices - device removed from joystick/android/inputdevice/6: Hisense (000D:3838)
> 2021-06-29 22:59:37.525 T:5050  WARNING <general>: CAndroidJoystickState: ignoring unknown axis 32 on input device "Hisense" with ID 7
> 2021-06-29 22:59:37.773 T:5050     INFO <general>: Register - new joystick device registered on android->android/inputdevice/7: Hisense (000D:3838)
```

 Error screenshot - 
![index](https://user-images.githubusercontent.com/78588173/123847222-f7ddcd80-d933-11eb-8de8-150b7f020e65.jpg)

**Comment by eintamil** [comment]
Hello, Can you please attach the screenshot of previous screen, where you
select the language.

**Comment by BeanedPaths** [comment]
Sure, here are the screenshot for different cases

Homepage
![homepage](https://user-images.githubusercontent.com/78588173/123911211-1c1fc580-d999-11eb-8125-47818d65e029.jpg)

Homepage/Tamil/Featured
![index](https://user-images.githubusercontent.com/78588173/123911639-aa944700-d999-11eb-9ccb-c62205cf0387.jpg)


Homepage/Tamil/Year/Years/2021
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/78588173/123912103-3d34e600-d99a-11eb-8bc1-dbe54158ef06.png">

Homepage/Malayalam/Year/Years/2021
![mal2021](https://user-images.githubusercontent.com/78588173/123911592-9b14fe00-d999-11eb-80f0-1b8e900b9cc4.jpg)

**Comment by eintamil** [comment]
I believe there is no connectivity between your device and Einthusan
website. Because, if everything were right, in the add-on homepage, you
should get thumbnail images for the languages. Please check the connection
and also check if the base URL value is correct in the add-on settings.

**Comment by eintamil** [comment]
Hello, Is this issue resolved. If yes, please close this ticket.

**Comment by BeanedPaths** [comment]
Yes, resolved the issue by using a VPN service. Thank you and closing the ticket.
